server:
  address: localhost
  port: 8080

spring:
  application:
    name: Lab4Mephi

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lab4
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    open-in-view: false
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console
